### ISSUE TITLE
"Debug: Shouldn't Happen" in combat.

### ISSUE THREAD

**Issue by blindndangerous** [pitermach/ReadTheSpire#1]
Whenever I start combat, and the screenreader is reading my enemy, their is always a debug message after intent. Intent: Debug: Shouldn't Happen. After this, it will continue on, then read the intent again correctly.
Player
Block: 0
Health: 77/80
Energy: 0
Monster
Count: 2
0: Spike Slime (S)
Block: 0
HP: 12/12
Intent: Debug (Shouldn't Happen)
1: Acid Slime (M)
Block: 0
HP: 30/30
Intent: Debug (Shouldn't Happen)
Player
Energy: 3
Monster
Incoming: 12
Intent: Attack 5
Intent: Attack/Debuff 7

**Comment by pitermach** [comment]
This is something that happens in TextTheSpire. Someone filed an issue for it there and it seems to happen when a battle starts but the game state hasn’t stabilized yet.

I’ll see if I can filter those out for the next version

From: blindndangerous
Sent: Wednesday, June 17, 2020 10:19 PM
To: pitermach/ReadTheSpire
Cc: Subscribed
Subject: [pitermach/ReadTheSpire] "Debug: Shouldn't Happen" in combat. (#1)

Whenever I start combat, and the screenreader is reading my enemy, their is always a debug message after intent. Intent: Debug: Shouldn't Happen. After this, it will continue on, then read the intent again correctly.
Player
Block: 0
Health: 77/80
Energy: 0
Monster
Count: 2
0: Spike Slime (S)
Block: 0
HP: 12/12
Intent: Debug (Shouldn't Happen)
1: Acid Slime (M)
Block: 0
HP: 30/30
Intent: Debug (Shouldn't Happen)
Player
Energy: 3
Monster
Incoming: 12
Intent: Attack 5
Intent: Attack/Debuff 7

**Comment by pitermach** [comment]
Fixed in [Version 3.0](https://github.com/pitermach/ReadTheSpire/releases/tag/3.0)
