### ISSUE TITLE
RTS stops speaking.

### ISSUE THREAD

**Issue by audiogamer22** [pitermach/ReadTheSpire#4]
I've made a post on audiogames.net but thought I'd copy it here and hope you see it.

I am having an issue with RTS, I type hide all, then map, find a map path I want to follow and type map 6 2, then choices and know I'm on the right path, I then go to attack a monster and the game stops talking, I can move and do things but the monster health isn't read out, mine isn't read out and basicly the speech stops.

Here's a little file showing you, I realised that showing the windows made the mod talk again, anyway here it is; https://www.dropbox.com/s/ql53uh0grwgg5qt/2020-07-02%2011_50.wav?dl=1

**Comment by pitermach** [comment]
This is normal. If you hide a window with the hide command, read the spire won't be able to monitor it. If you leave all the windows visible everything should work.
