### ISSUE TITLE
Read the spire does not work

### ISSUE THREAD

**Issue by Marc2p** [pitermach/ReadTheSpire#5]
I haven't played Slay the spire in a few months. Yesterday, when I wanted to play a game, I opened the game and found that Read the spire does not read me absolutely anything, nor can I even move through the different windows of the tex the spire accessibility mod.
When I type something in the prompt window it works, but the screen reader doesn't say anything. If I type quit, the game closes, but read the spire keeps running and I have to close it with ctrl + q.
Tried reinstalling the game, re-downloading read the spire, even running a clean copy of the screen reader, but nothing.

**Comment by pitermach** [comment]
Thanks for letting me know about this! I haven't played the game in a while either so was completely unaware this was broken.

Should be fixed in [Version 3.3](https://github.com/pitermach/ReadTheSpire/releases/tag/3.3). If it's still giving you problems, let me know.
